/**********************************************************************************************************************

 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *         File:  intCtr.h
 *       Module:  -
 *
 *  Description:  Control the interrupts
 *
 *********************************************************************************************************************/
#ifndef intCtr_Types_h
#define intCtr_Types_h

/**********************************************************************************************************************
 *  GLOBAL DATA TYPES AND STRUCTURES
 *********************************************************************************************************************/
typedef enum
{
    _INT0,
    _INT1,
    _INT2,
    _INT3,
    _INT4,
    _INT5,
    _INT6,
    _INT7,
    _INT8,
    _INT9,
    _INT10,
    _INT11,
    _INT12,
    _INT13,
    _INT14,
    _INT15,
    _INT16,
    _INT17,
    _INT18,
    _INT19,
    _INT20,
    _INT21,
    _INT22,
    _INT23,
    _INT24,
    _INT25,
    _INT26,
    _Reserved27,
    _INT28,
    _INT29,
    _INT30,
    _Reserved31,
    _Reserved32,
    _INT33,
    _INT34,
    _INT35,
    _INT36,
    _INT37,
    _INT38,
    _INT39,
    _INT40,
    _Reserved41,
    _Reserved42,
    _INT43,
    _INT44,
    _INT45,
    _INT46,
    _INT47,
    _INT48,
    _INT49,
    _INT50,
    _INT51,
    _Reserved52,
    _Reserved53,
    _Reserved54,
    _Reserved55,
    _Reserved56,
    _INT57,
    _INT58,
    _INT59,
    _INT60,
    _INT61,
    _INT62,
    _INT63,
    _Reserved64,
    _Reserved65,
    _Reserved66,
    _Reserved67,
    _INT68,
    _INT69,
    _INT70,
    _INT71,
    _Reserved72,
    _Reserved73,
    _Reserved74,
    _Reserved75,
    _Reserved76,
    _Reserved77,
    _Reserved78,
    _Reserved79,
    _Reserved80,
    _Reserved81,
    _Reserved82,
    _Reserved83,
    _Reserved84,
    _Reserved85,
    _Reserved86,
    _Reserved87,
    _Reserved88,
    _Reserved89,
    _Reserved90,
    _Reserved91,
    _INT92,
    _INT93,
    _INT94,
    _INT95,
    _INT96,
    _INT97,
    _INT98,
    _INT99,
    _INT100,
    _INT101,
    _INT102,
    _INT103,
    _INT104,
    _INT105,
    _INT106,
    _Reserved107,
    _Reserved108,
    _Reserved109,
    _Reserved110,
    _Reserved111,
    _Reserved112,
    _Reserved113,
    _Reserved114,
    _Reserved115,
    _Reserved116,
    _Reserved117,
    _Reserved118,
    _Reserved119,
    _Reserved120,
    _Reserved121,
    _Reserved122,
    _Reserved123,
    _Reserved124,
    _Reserved125,
    _Reserved126,
    _Reserved127,
    _Reserved128,
    _Reserved129,
    _Reserved130,
    _Reserved131,
    _Reserved132,
    _Reserved133,
    _INT134,
    _INT135,
    _INT136,
    _INT137,
    _INT138,
    NONE
} IntCtrNum_t;

typedef enum
{
    Memory_Management_Fault,
    Bus_Fault,
    Usage_Fault,
    SVCall,
    Debug,
    PendSV,
    SysTick_Exception

} ExceptionNum_t;

#endif /* intCtr_Types_h */

/**********************************************************************************************************************
 *  END OF FILE: intCtr_Types.h
 *********************************************************************************************************************/
