/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/**        \file  PORT_Cfg.c
 *        \brief  Configure all pins of the MicroController
 *      \details  Contains:
 *                PORT_Cfg_Arr[] Array
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "PORT_Cfg.h"

/**********************************************************************************************************************
 *  GLOBAL DATA
 *********************************************************************************************************************/
/*
 * The configuration array "PORT_Cfg_Arr" that is declared,
 * which contains several parameters for configuring
 * each pin of each port. These parameters include:
 *      Port name (Not configurable),
 *      Pin number(Not configurable),
 *      Digital Enable (DIGITAL_ENABLE / DIGITAL_DISNABLE),
 *      Alternate Pin Enable (ALTERNATE_ENABLE / ALTERNATE_DISABLE),
 *      Alternate Function Number (NONE_FNC / UART / I2C / M0PWM / M1PWM / TxCCPx ),
 *      Direction (OUTPUT / INPUT),
 *      Level (HIGH / LOW),
 *      and Connection Type (FLOATING_PIN / POLLUP / POLLDOWN / OPEN_DRAIN).
 * */

PORT_Cfg_t PORT_Cfg_Arr[] = {
    {PORTA, PORT_Pin0, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTA, PORT_Pin1, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTA, PORT_Pin2, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},  //Ultrasonic trig
    {PORTA, PORT_Pin3, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTA, PORT_Pin4, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, HIGH, FLOATING_PIN},
    {PORTA, PORT_Pin5, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTA, PORT_Pin6, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, HIGH, FLOATING_PIN},
    {PORTA, PORT_Pin7, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, HIGH, FLOATING_PIN},

    {PORTB, PORT_Pin0, DIGITAL_ENABLE, ALTERNATE_ENABLE, UART, INPUT, LOW, FLOATING_PIN},
    {PORTB, PORT_Pin1, DIGITAL_ENABLE, ALTERNATE_ENABLE, UART, OUTPUT, LOW, FLOATING_PIN},
    {PORTB, PORT_Pin2, DIGITAL_ENABLE, ALTERNATE_ENABLE, TxCCPx, INPUT, LOW, FLOATING_PIN},  //T3CCP0  //Ultrasonic echo
    {PORTB, PORT_Pin3, DIGITAL_ENABLE, ALTERNATE_ENABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTB, PORT_Pin4, DIGITAL_ENABLE, ALTERNATE_ENABLE, M0PWM, OUTPUT, LOW, FLOATING_PIN},
    {PORTB, PORT_Pin5, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTB, PORT_Pin6, DIGITAL_ENABLE, ALTERNATE_ENABLE, M0PWM, OUTPUT, LOW, FLOATING_PIN},  /////timer pwm
    {PORTB, PORT_Pin7, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},

    {PORTC, PORT_Pin0, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, INPUT, LOW, FLOATING_PIN},  //DEBUG
    {PORTC, PORT_Pin1, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN}, //DEBUG
    {PORTC, PORT_Pin2, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN}, //DEBUG
    {PORTC, PORT_Pin3, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN}, //DEBUG
    {PORTC, PORT_Pin4, DIGITAL_ENABLE, ALTERNATE_ENABLE, UART, INPUT, LOW, FLOATING_PIN},
    {PORTC, PORT_Pin5, DIGITAL_ENABLE, ALTERNATE_ENABLE, UART, OUTPUT, LOW, FLOATING_PIN},
    {PORTC, PORT_Pin6, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTC, PORT_Pin7, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},

    {PORTD, PORT_Pin0, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTD, PORT_Pin1, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTD, PORT_Pin2, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTD, PORT_Pin3, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTD, PORT_Pin4, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTD, PORT_Pin5, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTD, PORT_Pin6, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTD, PORT_Pin7, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},

    {PORTE, PORT_Pin0, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTE, PORT_Pin1, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTE, PORT_Pin2, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTE, PORT_Pin3, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTE, PORT_Pin4, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTE, PORT_Pin5, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTE, PORT_Pin6, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTE, PORT_Pin7, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},

    {PORTF, PORT_Pin0, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, INPUT, LOW, POLLUP},
    {PORTF, PORT_Pin1, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTF, PORT_Pin2, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTF, PORT_Pin3, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, OUTPUT, LOW, FLOATING_PIN},
    {PORTF, PORT_Pin4, DIGITAL_ENABLE, ALTERNATE_DISABLE, NONE_FNC, INPUT, LOW, POLLUP},};
/**********************************************************************************************************************
 *  END OF FILE: PORT_Cfg.c
 *********************************************************************************************************************/
